name: Test docker image
run-name: Version checking / Testing
on:
    schedule:
        - cron: '0 0 * * *'
    workflow_dispatch:
env:
  TEST_TAG: wovnep/pocketbase:test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm install semver-compare
      - uses: actions/github-script@v7
        id: set-result
        with:
          script: |
            const cmp = require('semver-compare')
            const release =  await github.rest.repos.getLatestRelease({
              owner: "pocketbase",
              repo: "pocketbase",
            })
            const version = release.data.tag_name.split("v")[1]
            const tags =  await github.rest.repos.listTags({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            let current_version = tags.data[0]?.name || "0.19.3"
            if(cmp(version,current_version) == 1){
              return version
            } else {
              core.setFailed(`No new releases found. Latest release: ${version}`);
            }
          result-encoding: string
      - name: Checkout
        uses: actions/checkout@v4
      - name: Building the image
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: |
            VERSION=${{steps.set-result.outputs.result}}
          tags: ${{ env.TEST_TAG }}
      - name: Testing the image
        run: |
          source test.sh
      - uses: actions/github-script@v7
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{steps.set-result.outputs.result}}',
              sha: context.sha
            })